backend:
  name: git-gateway
  branch: master

# By default, saving a post in the CMS
# interface pushes a commit directly to
# the publication branch specified in backend.
# However, you also have the option to enable
# the Editorial Workflow, which adds an interface
# for drafting, reviewing, and approving posts.
publish_mode: editorial_workflow

media_folder: "images"

collections:
  # Our pages e.g. Home
  - name: "pages"
    label: "Page"
    folder: "src/pages"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Hero heading", name: "hero_heading", widget: "string" }
      - { label: "Hero description", name: "hero_description", widget: "string" }
      - { label: "Hero image", name: "hero_image", widget: "image", default: "images/Homepage_Hero.svg" }
      - { label: "Heading 1", name: "heading1", widget: "string" }
      - { label: "Description 1", name: "description1", widget: "string" }
      - { label: "Image 1", name: "image1", widget: "image", default: "images/Homepage_Threading1.svg"}
  
  - name: "testimonials"
    label: "Testimonials"
    identifier_field: "company"
    folder: "src/data"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Author avatar", name: "image", widget: "image"}
      - { label: "Author name", name: "author", widget: "text"}
      - { label: "Author designation", name: "designation", widget: "text"}
      - { label: "Company", name: "company", widget: "text"}
      - { label: "Quote", name: "quote", widget: "text"}
      - { label: "Tags", name: "tags", widget: "text", default: "testimonial"}
      - { label: "First active", name: "active", widget: "boolean", default: false}
